### ISSUE TITLE
other currencies 

### ISSUE THREAD

**Issue by MCM-Mike** [firebase/btcquote#8]
are you planning to add EUR to your widget ?

**Comment by kalibri** [comment]
да планирую

**Comment by ulkas** [comment]
@MCM-Mike maybe check my older project, which used to work for plenty currencies:
https://github.com/ulkas/CryptoTools

not sure if the main exchanges i was taking the real-time price data are still active, but once you check the simple code you'll know how to add one

**Comment by Goatform** [comment]
Nice :+1
